/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserManagementIndexRouteImport } from './routes/user-management.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as UserManagementUserCreationRouteImport } from './routes/user-management.user-creation'
import { Route as UserManagementAllUsersRouteImport } from './routes/user-management.all-users'
import { Route as UserManagementAccessPolicyRouteImport } from './routes/user-management.access-policy'
import { Route as CasesMyOpenCasesRouteImport } from './routes/cases.my-open-cases'
import { Route as CasesMyClosedCasesRouteImport } from './routes/cases.my-closed-cases'
import { Route as CasesAllCasesRouteImport } from './routes/cases.all-cases'

const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementIndexRoute = UserManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserManagementRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const UserManagementUserCreationRoute =
  UserManagementUserCreationRouteImport.update({
    id: '/user-creation',
    path: '/user-creation',
    getParentRoute: () => UserManagementRoute,
  } as any)
const UserManagementAllUsersRoute = UserManagementAllUsersRouteImport.update({
  id: '/all-users',
  path: '/all-users',
  getParentRoute: () => UserManagementRoute,
} as any)
const UserManagementAccessPolicyRoute =
  UserManagementAccessPolicyRouteImport.update({
    id: '/access-policy',
    path: '/access-policy',
    getParentRoute: () => UserManagementRoute,
  } as any)
const CasesMyOpenCasesRoute = CasesMyOpenCasesRouteImport.update({
  id: '/my-open-cases',
  path: '/my-open-cases',
  getParentRoute: () => CasesRoute,
} as any)
const CasesMyClosedCasesRoute = CasesMyClosedCasesRouteImport.update({
  id: '/my-closed-cases',
  path: '/my-closed-cases',
  getParentRoute: () => CasesRoute,
} as any)
const CasesAllCasesRoute = CasesAllCasesRouteImport.update({
  id: '/all-cases',
  path: '/all-cases',
  getParentRoute: () => CasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/mcp': typeof McpRoute
  '/merchants': typeof MerchantsRoute
  '/user-management': typeof UserManagementRouteWithChildren
  '/cases/all-cases': typeof CasesAllCasesRoute
  '/cases/my-closed-cases': typeof CasesMyClosedCasesRoute
  '/cases/my-open-cases': typeof CasesMyOpenCasesRoute
  '/user-management/access-policy': typeof UserManagementAccessPolicyRoute
  '/user-management/all-users': typeof UserManagementAllUsersRoute
  '/user-management/user-creation': typeof UserManagementUserCreationRoute
  '/cases/': typeof CasesIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/merchants': typeof MerchantsRoute
  '/cases/all-cases': typeof CasesAllCasesRoute
  '/cases/my-closed-cases': typeof CasesMyClosedCasesRoute
  '/cases/my-open-cases': typeof CasesMyOpenCasesRoute
  '/user-management/access-policy': typeof UserManagementAccessPolicyRoute
  '/user-management/all-users': typeof UserManagementAllUsersRoute
  '/user-management/user-creation': typeof UserManagementUserCreationRoute
  '/cases': typeof CasesIndexRoute
  '/user-management': typeof UserManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/mcp': typeof McpRoute
  '/merchants': typeof MerchantsRoute
  '/user-management': typeof UserManagementRouteWithChildren
  '/cases/all-cases': typeof CasesAllCasesRoute
  '/cases/my-closed-cases': typeof CasesMyClosedCasesRoute
  '/cases/my-open-cases': typeof CasesMyOpenCasesRoute
  '/user-management/access-policy': typeof UserManagementAccessPolicyRoute
  '/user-management/all-users': typeof UserManagementAllUsersRoute
  '/user-management/user-creation': typeof UserManagementUserCreationRoute
  '/cases/': typeof CasesIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/mcp'
    | '/merchants'
    | '/user-management'
    | '/cases/all-cases'
    | '/cases/my-closed-cases'
    | '/cases/my-open-cases'
    | '/user-management/access-policy'
    | '/user-management/all-users'
    | '/user-management/user-creation'
    | '/cases/'
    | '/user-management/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/merchants'
    | '/cases/all-cases'
    | '/cases/my-closed-cases'
    | '/cases/my-open-cases'
    | '/user-management/access-policy'
    | '/user-management/all-users'
    | '/user-management/user-creation'
    | '/cases'
    | '/user-management'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/mcp'
    | '/merchants'
    | '/user-management'
    | '/cases/all-cases'
    | '/cases/my-closed-cases'
    | '/cases/my-open-cases'
    | '/user-management/access-policy'
    | '/user-management/all-users'
    | '/user-management/user-creation'
    | '/cases/'
    | '/user-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRouteWithChildren
  McpRoute: typeof McpRoute
  MerchantsRoute: typeof MerchantsRoute
  UserManagementRoute: typeof UserManagementRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/': {
      id: '/user-management/'
      path: '/'
      fullPath: '/user-management/'
      preLoaderRoute: typeof UserManagementIndexRouteImport
      parentRoute: typeof UserManagementRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/user-management/user-creation': {
      id: '/user-management/user-creation'
      path: '/user-creation'
      fullPath: '/user-management/user-creation'
      preLoaderRoute: typeof UserManagementUserCreationRouteImport
      parentRoute: typeof UserManagementRoute
    }
    '/user-management/all-users': {
      id: '/user-management/all-users'
      path: '/all-users'
      fullPath: '/user-management/all-users'
      preLoaderRoute: typeof UserManagementAllUsersRouteImport
      parentRoute: typeof UserManagementRoute
    }
    '/user-management/access-policy': {
      id: '/user-management/access-policy'
      path: '/access-policy'
      fullPath: '/user-management/access-policy'
      preLoaderRoute: typeof UserManagementAccessPolicyRouteImport
      parentRoute: typeof UserManagementRoute
    }
    '/cases/my-open-cases': {
      id: '/cases/my-open-cases'
      path: '/my-open-cases'
      fullPath: '/cases/my-open-cases'
      preLoaderRoute: typeof CasesMyOpenCasesRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/my-closed-cases': {
      id: '/cases/my-closed-cases'
      path: '/my-closed-cases'
      fullPath: '/cases/my-closed-cases'
      preLoaderRoute: typeof CasesMyClosedCasesRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/all-cases': {
      id: '/cases/all-cases'
      path: '/all-cases'
      fullPath: '/cases/all-cases'
      preLoaderRoute: typeof CasesAllCasesRouteImport
      parentRoute: typeof CasesRoute
    }
  }
}

interface CasesRouteChildren {
  CasesAllCasesRoute: typeof CasesAllCasesRoute
  CasesMyClosedCasesRoute: typeof CasesMyClosedCasesRoute
  CasesMyOpenCasesRoute: typeof CasesMyOpenCasesRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesAllCasesRoute: CasesAllCasesRoute,
  CasesMyClosedCasesRoute: CasesMyClosedCasesRoute,
  CasesMyOpenCasesRoute: CasesMyOpenCasesRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface UserManagementRouteChildren {
  UserManagementAccessPolicyRoute: typeof UserManagementAccessPolicyRoute
  UserManagementAllUsersRoute: typeof UserManagementAllUsersRoute
  UserManagementUserCreationRoute: typeof UserManagementUserCreationRoute
  UserManagementIndexRoute: typeof UserManagementIndexRoute
}

const UserManagementRouteChildren: UserManagementRouteChildren = {
  UserManagementAccessPolicyRoute: UserManagementAccessPolicyRoute,
  UserManagementAllUsersRoute: UserManagementAllUsersRoute,
  UserManagementUserCreationRoute: UserManagementUserCreationRoute,
  UserManagementIndexRoute: UserManagementIndexRoute,
}

const UserManagementRouteWithChildren = UserManagementRoute._addFileChildren(
  UserManagementRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRouteWithChildren,
  McpRoute: McpRoute,
  MerchantsRoute: MerchantsRoute,
  UserManagementRoute: UserManagementRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
