/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingFormRouteImport } from './routes/onboarding-form'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OnboardingFormIndexRouteImport } from './routes/onboarding-form.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as SetPasswordTokenRouteImport } from './routes/set-password.$token'
import { Route as AppUserManagementRouteImport } from './routes/_app.user-management'
import { Route as AppMerchantsRouteImport } from './routes/_app.merchants'
import { Route as AppConfigurationRouteImport } from './routes/_app.configuration'
import { Route as AppCasesRouteImport } from './routes/_app.cases'
import { Route as AppUserManagementIndexRouteImport } from './routes/_app.user-management.index'
import { Route as AppMerchantsIndexRouteImport } from './routes/_app.merchants.index'
import { Route as AppConfigurationIndexRouteImport } from './routes/_app.configuration.index'
import { Route as AppCasesIndexRouteImport } from './routes/_app.cases.index'
import { Route as OnboardingFormResubmitTokenRouteImport } from './routes/onboarding-form.resubmit.$token'
import { Route as OnboardingFormGoLiveTokenRouteImport } from './routes/onboarding-form.go-live.$token'
import { Route as OnboardingFormAgreementTokenRouteImport } from './routes/onboarding-form.agreement.$token'
import { Route as AppUserManagementUserCreationRouteImport } from './routes/_app.user-management.user-creation'
import { Route as AppUserManagementAllUsersRouteImport } from './routes/_app.user-management.all-users'
import { Route as AppMerchantsMerchantIdRouteImport } from './routes/_app.merchants.$merchantId'
import { Route as AppConfigurationSubMerchantsRouteImport } from './routes/_app.configuration.sub-merchants'
import { Route as AppConfigurationQueuesRouteImport } from './routes/_app.configuration.queues'
import { Route as AppConfigurationMerchantPortalRouteImport } from './routes/_app.configuration.merchant-portal'
import { Route as AppConfigurationLinkDeadlinesRouteImport } from './routes/_app.configuration.link-deadlines'
import { Route as AppConfigurationLimitsAndMdrRouteImport } from './routes/_app.configuration.limits-and-mdr'
import { Route as AppConfigurationEmailSendingRouteImport } from './routes/_app.configuration.email-sending'
import { Route as AppConfigurationCaseTriggeringRouteImport } from './routes/_app.configuration.case-triggering'
import { Route as AppConfigurationCaseFlowRulesRouteImport } from './routes/_app.configuration.case-flow-rules'
import { Route as AppConfigurationAgreementsRouteImport } from './routes/_app.configuration.agreements'
import { Route as AppCasesMyOpenCasesRouteImport } from './routes/_app.cases.my-open-cases'
import { Route as AppCasesMyClosedCasesRouteImport } from './routes/_app.cases.my-closed-cases'
import { Route as AppCasesAllCasesRouteImport } from './routes/_app.cases.all-cases'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app.cases.$caseId'
import { Route as AppUserManagementUsersUserIdRouteImport } from './routes/_app.user-management.users.$userId'

const OnboardingFormRoute = OnboardingFormRouteImport.update({
  id: '/onboarding-form',
  path: '/onboarding-form',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFormIndexRoute = OnboardingFormIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingFormRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SetPasswordTokenRoute = SetPasswordTokenRouteImport.update({
  id: '/set-password/$token',
  path: '/set-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserManagementRoute = AppUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => AppRoute,
} as any)
const AppMerchantsRoute = AppMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigurationRoute = AppConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppUserManagementIndexRoute = AppUserManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUserManagementRoute,
} as any)
const AppMerchantsIndexRoute = AppMerchantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMerchantsRoute,
} as any)
const AppConfigurationIndexRoute = AppConfigurationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfigurationRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCasesRoute,
} as any)
const OnboardingFormResubmitTokenRoute =
  OnboardingFormResubmitTokenRouteImport.update({
    id: '/resubmit/$token',
    path: '/resubmit/$token',
    getParentRoute: () => OnboardingFormRoute,
  } as any)
const OnboardingFormGoLiveTokenRoute =
  OnboardingFormGoLiveTokenRouteImport.update({
    id: '/go-live/$token',
    path: '/go-live/$token',
    getParentRoute: () => OnboardingFormRoute,
  } as any)
const OnboardingFormAgreementTokenRoute =
  OnboardingFormAgreementTokenRouteImport.update({
    id: '/agreement/$token',
    path: '/agreement/$token',
    getParentRoute: () => OnboardingFormRoute,
  } as any)
const AppUserManagementUserCreationRoute =
  AppUserManagementUserCreationRouteImport.update({
    id: '/user-creation',
    path: '/user-creation',
    getParentRoute: () => AppUserManagementRoute,
  } as any)
const AppUserManagementAllUsersRoute =
  AppUserManagementAllUsersRouteImport.update({
    id: '/all-users',
    path: '/all-users',
    getParentRoute: () => AppUserManagementRoute,
  } as any)
const AppMerchantsMerchantIdRoute = AppMerchantsMerchantIdRouteImport.update({
  id: '/$merchantId',
  path: '/$merchantId',
  getParentRoute: () => AppMerchantsRoute,
} as any)
const AppConfigurationSubMerchantsRoute =
  AppConfigurationSubMerchantsRouteImport.update({
    id: '/sub-merchants',
    path: '/sub-merchants',
    getParentRoute: () => AppConfigurationRoute,
  } as any)
const AppConfigurationQueuesRoute = AppConfigurationQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => AppConfigurationRoute,
} as any)
const AppConfigurationMerchantPortalRoute =
  AppConfigurationMerchantPortalRouteImport.update({
    id: '/merchant-portal',
    path: '/merchant-portal',
    getParentRoute: () => AppConfigurationRoute,
  } as any)
const AppConfigurationLinkDeadlinesRoute =
  AppConfigurationLinkDeadlinesRouteImport.update({
    id: '/link-deadlines',
    path: '/link-deadlines',
    getParentRoute: () => AppConfigurationRoute,
  } as any)
const AppConfigurationLimitsAndMdrRoute =
  AppConfigurationLimitsAndMdrRouteImport.update({
    id: '/limits-and-mdr',
    path: '/limits-and-mdr',
    getParentRoute: () => AppConfigurationRoute,
  } as any)
const AppConfigurationEmailSendingRoute =
  AppConfigurationEmailSendingRouteImport.update({
    id: '/email-sending',
    path: '/email-sending',
    getParentRoute: () => AppConfigurationRoute,
  } as any)
const AppConfigurationCaseTriggeringRoute =
  AppConfigurationCaseTriggeringRouteImport.update({
    id: '/case-triggering',
    path: '/case-triggering',
    getParentRoute: () => AppConfigurationRoute,
  } as any)
const AppConfigurationCaseFlowRulesRoute =
  AppConfigurationCaseFlowRulesRouteImport.update({
    id: '/case-flow-rules',
    path: '/case-flow-rules',
    getParentRoute: () => AppConfigurationRoute,
  } as any)
const AppConfigurationAgreementsRoute =
  AppConfigurationAgreementsRouteImport.update({
    id: '/agreements',
    path: '/agreements',
    getParentRoute: () => AppConfigurationRoute,
  } as any)
const AppCasesMyOpenCasesRoute = AppCasesMyOpenCasesRouteImport.update({
  id: '/my-open-cases',
  path: '/my-open-cases',
  getParentRoute: () => AppCasesRoute,
} as any)
const AppCasesMyClosedCasesRoute = AppCasesMyClosedCasesRouteImport.update({
  id: '/my-closed-cases',
  path: '/my-closed-cases',
  getParentRoute: () => AppCasesRoute,
} as any)
const AppCasesAllCasesRoute = AppCasesAllCasesRouteImport.update({
  id: '/all-cases',
  path: '/all-cases',
  getParentRoute: () => AppCasesRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AppCasesRoute,
} as any)
const AppUserManagementUsersUserIdRoute =
  AppUserManagementUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AppUserManagementRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding-form': typeof OnboardingFormRouteWithChildren
  '/cases': typeof AppCasesRouteWithChildren
  '/configuration': typeof AppConfigurationRouteWithChildren
  '/merchants': typeof AppMerchantsRouteWithChildren
  '/user-management': typeof AppUserManagementRouteWithChildren
  '/set-password/$token': typeof SetPasswordTokenRoute
  '/onboarding-form/': typeof OnboardingFormIndexRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/cases/all-cases': typeof AppCasesAllCasesRoute
  '/cases/my-closed-cases': typeof AppCasesMyClosedCasesRoute
  '/cases/my-open-cases': typeof AppCasesMyOpenCasesRoute
  '/configuration/agreements': typeof AppConfigurationAgreementsRoute
  '/configuration/case-flow-rules': typeof AppConfigurationCaseFlowRulesRoute
  '/configuration/case-triggering': typeof AppConfigurationCaseTriggeringRoute
  '/configuration/email-sending': typeof AppConfigurationEmailSendingRoute
  '/configuration/limits-and-mdr': typeof AppConfigurationLimitsAndMdrRoute
  '/configuration/link-deadlines': typeof AppConfigurationLinkDeadlinesRoute
  '/configuration/merchant-portal': typeof AppConfigurationMerchantPortalRoute
  '/configuration/queues': typeof AppConfigurationQueuesRoute
  '/configuration/sub-merchants': typeof AppConfigurationSubMerchantsRoute
  '/merchants/$merchantId': typeof AppMerchantsMerchantIdRoute
  '/user-management/all-users': typeof AppUserManagementAllUsersRoute
  '/user-management/user-creation': typeof AppUserManagementUserCreationRoute
  '/onboarding-form/agreement/$token': typeof OnboardingFormAgreementTokenRoute
  '/onboarding-form/go-live/$token': typeof OnboardingFormGoLiveTokenRoute
  '/onboarding-form/resubmit/$token': typeof OnboardingFormResubmitTokenRoute
  '/cases/': typeof AppCasesIndexRoute
  '/configuration/': typeof AppConfigurationIndexRoute
  '/merchants/': typeof AppMerchantsIndexRoute
  '/user-management/': typeof AppUserManagementIndexRoute
  '/user-management/users/$userId': typeof AppUserManagementUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/set-password/$token': typeof SetPasswordTokenRoute
  '/': typeof AppIndexRoute
  '/onboarding-form': typeof OnboardingFormIndexRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/cases/all-cases': typeof AppCasesAllCasesRoute
  '/cases/my-closed-cases': typeof AppCasesMyClosedCasesRoute
  '/cases/my-open-cases': typeof AppCasesMyOpenCasesRoute
  '/configuration/agreements': typeof AppConfigurationAgreementsRoute
  '/configuration/case-flow-rules': typeof AppConfigurationCaseFlowRulesRoute
  '/configuration/case-triggering': typeof AppConfigurationCaseTriggeringRoute
  '/configuration/email-sending': typeof AppConfigurationEmailSendingRoute
  '/configuration/limits-and-mdr': typeof AppConfigurationLimitsAndMdrRoute
  '/configuration/link-deadlines': typeof AppConfigurationLinkDeadlinesRoute
  '/configuration/merchant-portal': typeof AppConfigurationMerchantPortalRoute
  '/configuration/queues': typeof AppConfigurationQueuesRoute
  '/configuration/sub-merchants': typeof AppConfigurationSubMerchantsRoute
  '/merchants/$merchantId': typeof AppMerchantsMerchantIdRoute
  '/user-management/all-users': typeof AppUserManagementAllUsersRoute
  '/user-management/user-creation': typeof AppUserManagementUserCreationRoute
  '/onboarding-form/agreement/$token': typeof OnboardingFormAgreementTokenRoute
  '/onboarding-form/go-live/$token': typeof OnboardingFormGoLiveTokenRoute
  '/onboarding-form/resubmit/$token': typeof OnboardingFormResubmitTokenRoute
  '/cases': typeof AppCasesIndexRoute
  '/configuration': typeof AppConfigurationIndexRoute
  '/merchants': typeof AppMerchantsIndexRoute
  '/user-management': typeof AppUserManagementIndexRoute
  '/user-management/users/$userId': typeof AppUserManagementUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding-form': typeof OnboardingFormRouteWithChildren
  '/_app/cases': typeof AppCasesRouteWithChildren
  '/_app/configuration': typeof AppConfigurationRouteWithChildren
  '/_app/merchants': typeof AppMerchantsRouteWithChildren
  '/_app/user-management': typeof AppUserManagementRouteWithChildren
  '/set-password/$token': typeof SetPasswordTokenRoute
  '/_app/': typeof AppIndexRoute
  '/onboarding-form/': typeof OnboardingFormIndexRoute
  '/_app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/_app/cases/all-cases': typeof AppCasesAllCasesRoute
  '/_app/cases/my-closed-cases': typeof AppCasesMyClosedCasesRoute
  '/_app/cases/my-open-cases': typeof AppCasesMyOpenCasesRoute
  '/_app/configuration/agreements': typeof AppConfigurationAgreementsRoute
  '/_app/configuration/case-flow-rules': typeof AppConfigurationCaseFlowRulesRoute
  '/_app/configuration/case-triggering': typeof AppConfigurationCaseTriggeringRoute
  '/_app/configuration/email-sending': typeof AppConfigurationEmailSendingRoute
  '/_app/configuration/limits-and-mdr': typeof AppConfigurationLimitsAndMdrRoute
  '/_app/configuration/link-deadlines': typeof AppConfigurationLinkDeadlinesRoute
  '/_app/configuration/merchant-portal': typeof AppConfigurationMerchantPortalRoute
  '/_app/configuration/queues': typeof AppConfigurationQueuesRoute
  '/_app/configuration/sub-merchants': typeof AppConfigurationSubMerchantsRoute
  '/_app/merchants/$merchantId': typeof AppMerchantsMerchantIdRoute
  '/_app/user-management/all-users': typeof AppUserManagementAllUsersRoute
  '/_app/user-management/user-creation': typeof AppUserManagementUserCreationRoute
  '/onboarding-form/agreement/$token': typeof OnboardingFormAgreementTokenRoute
  '/onboarding-form/go-live/$token': typeof OnboardingFormGoLiveTokenRoute
  '/onboarding-form/resubmit/$token': typeof OnboardingFormResubmitTokenRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/configuration/': typeof AppConfigurationIndexRoute
  '/_app/merchants/': typeof AppMerchantsIndexRoute
  '/_app/user-management/': typeof AppUserManagementIndexRoute
  '/_app/user-management/users/$userId': typeof AppUserManagementUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/onboarding-form'
    | '/cases'
    | '/configuration'
    | '/merchants'
    | '/user-management'
    | '/set-password/$token'
    | '/onboarding-form/'
    | '/cases/$caseId'
    | '/cases/all-cases'
    | '/cases/my-closed-cases'
    | '/cases/my-open-cases'
    | '/configuration/agreements'
    | '/configuration/case-flow-rules'
    | '/configuration/case-triggering'
    | '/configuration/email-sending'
    | '/configuration/limits-and-mdr'
    | '/configuration/link-deadlines'
    | '/configuration/merchant-portal'
    | '/configuration/queues'
    | '/configuration/sub-merchants'
    | '/merchants/$merchantId'
    | '/user-management/all-users'
    | '/user-management/user-creation'
    | '/onboarding-form/agreement/$token'
    | '/onboarding-form/go-live/$token'
    | '/onboarding-form/resubmit/$token'
    | '/cases/'
    | '/configuration/'
    | '/merchants/'
    | '/user-management/'
    | '/user-management/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/mcp'
    | '/set-password/$token'
    | '/'
    | '/onboarding-form'
    | '/cases/$caseId'
    | '/cases/all-cases'
    | '/cases/my-closed-cases'
    | '/cases/my-open-cases'
    | '/configuration/agreements'
    | '/configuration/case-flow-rules'
    | '/configuration/case-triggering'
    | '/configuration/email-sending'
    | '/configuration/limits-and-mdr'
    | '/configuration/link-deadlines'
    | '/configuration/merchant-portal'
    | '/configuration/queues'
    | '/configuration/sub-merchants'
    | '/merchants/$merchantId'
    | '/user-management/all-users'
    | '/user-management/user-creation'
    | '/onboarding-form/agreement/$token'
    | '/onboarding-form/go-live/$token'
    | '/onboarding-form/resubmit/$token'
    | '/cases'
    | '/configuration'
    | '/merchants'
    | '/user-management'
    | '/user-management/users/$userId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/mcp'
    | '/onboarding-form'
    | '/_app/cases'
    | '/_app/configuration'
    | '/_app/merchants'
    | '/_app/user-management'
    | '/set-password/$token'
    | '/_app/'
    | '/onboarding-form/'
    | '/_app/cases/$caseId'
    | '/_app/cases/all-cases'
    | '/_app/cases/my-closed-cases'
    | '/_app/cases/my-open-cases'
    | '/_app/configuration/agreements'
    | '/_app/configuration/case-flow-rules'
    | '/_app/configuration/case-triggering'
    | '/_app/configuration/email-sending'
    | '/_app/configuration/limits-and-mdr'
    | '/_app/configuration/link-deadlines'
    | '/_app/configuration/merchant-portal'
    | '/_app/configuration/queues'
    | '/_app/configuration/sub-merchants'
    | '/_app/merchants/$merchantId'
    | '/_app/user-management/all-users'
    | '/_app/user-management/user-creation'
    | '/onboarding-form/agreement/$token'
    | '/onboarding-form/go-live/$token'
    | '/onboarding-form/resubmit/$token'
    | '/_app/cases/'
    | '/_app/configuration/'
    | '/_app/merchants/'
    | '/_app/user-management/'
    | '/_app/user-management/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingFormRoute: typeof OnboardingFormRouteWithChildren
  SetPasswordTokenRoute: typeof SetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding-form': {
      id: '/onboarding-form'
      path: '/onboarding-form'
      fullPath: '/onboarding-form'
      preLoaderRoute: typeof OnboardingFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-form/': {
      id: '/onboarding-form/'
      path: '/'
      fullPath: '/onboarding-form/'
      preLoaderRoute: typeof OnboardingFormIndexRouteImport
      parentRoute: typeof OnboardingFormRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/set-password/$token': {
      id: '/set-password/$token'
      path: '/set-password/$token'
      fullPath: '/set-password/$token'
      preLoaderRoute: typeof SetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/user-management': {
      id: '/_app/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AppUserManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/merchants': {
      id: '/_app/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof AppMerchantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuration': {
      id: '/_app/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof AppConfigurationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user-management/': {
      id: '/_app/user-management/'
      path: '/'
      fullPath: '/user-management/'
      preLoaderRoute: typeof AppUserManagementIndexRouteImport
      parentRoute: typeof AppUserManagementRoute
    }
    '/_app/merchants/': {
      id: '/_app/merchants/'
      path: '/'
      fullPath: '/merchants/'
      preLoaderRoute: typeof AppMerchantsIndexRouteImport
      parentRoute: typeof AppMerchantsRoute
    }
    '/_app/configuration/': {
      id: '/_app/configuration/'
      path: '/'
      fullPath: '/configuration/'
      preLoaderRoute: typeof AppConfigurationIndexRouteImport
      parentRoute: typeof AppConfigurationRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/onboarding-form/resubmit/$token': {
      id: '/onboarding-form/resubmit/$token'
      path: '/resubmit/$token'
      fullPath: '/onboarding-form/resubmit/$token'
      preLoaderRoute: typeof OnboardingFormResubmitTokenRouteImport
      parentRoute: typeof OnboardingFormRoute
    }
    '/onboarding-form/go-live/$token': {
      id: '/onboarding-form/go-live/$token'
      path: '/go-live/$token'
      fullPath: '/onboarding-form/go-live/$token'
      preLoaderRoute: typeof OnboardingFormGoLiveTokenRouteImport
      parentRoute: typeof OnboardingFormRoute
    }
    '/onboarding-form/agreement/$token': {
      id: '/onboarding-form/agreement/$token'
      path: '/agreement/$token'
      fullPath: '/onboarding-form/agreement/$token'
      preLoaderRoute: typeof OnboardingFormAgreementTokenRouteImport
      parentRoute: typeof OnboardingFormRoute
    }
    '/_app/user-management/user-creation': {
      id: '/_app/user-management/user-creation'
      path: '/user-creation'
      fullPath: '/user-management/user-creation'
      preLoaderRoute: typeof AppUserManagementUserCreationRouteImport
      parentRoute: typeof AppUserManagementRoute
    }
    '/_app/user-management/all-users': {
      id: '/_app/user-management/all-users'
      path: '/all-users'
      fullPath: '/user-management/all-users'
      preLoaderRoute: typeof AppUserManagementAllUsersRouteImport
      parentRoute: typeof AppUserManagementRoute
    }
    '/_app/merchants/$merchantId': {
      id: '/_app/merchants/$merchantId'
      path: '/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof AppMerchantsMerchantIdRouteImport
      parentRoute: typeof AppMerchantsRoute
    }
    '/_app/configuration/sub-merchants': {
      id: '/_app/configuration/sub-merchants'
      path: '/sub-merchants'
      fullPath: '/configuration/sub-merchants'
      preLoaderRoute: typeof AppConfigurationSubMerchantsRouteImport
      parentRoute: typeof AppConfigurationRoute
    }
    '/_app/configuration/queues': {
      id: '/_app/configuration/queues'
      path: '/queues'
      fullPath: '/configuration/queues'
      preLoaderRoute: typeof AppConfigurationQueuesRouteImport
      parentRoute: typeof AppConfigurationRoute
    }
    '/_app/configuration/merchant-portal': {
      id: '/_app/configuration/merchant-portal'
      path: '/merchant-portal'
      fullPath: '/configuration/merchant-portal'
      preLoaderRoute: typeof AppConfigurationMerchantPortalRouteImport
      parentRoute: typeof AppConfigurationRoute
    }
    '/_app/configuration/link-deadlines': {
      id: '/_app/configuration/link-deadlines'
      path: '/link-deadlines'
      fullPath: '/configuration/link-deadlines'
      preLoaderRoute: typeof AppConfigurationLinkDeadlinesRouteImport
      parentRoute: typeof AppConfigurationRoute
    }
    '/_app/configuration/limits-and-mdr': {
      id: '/_app/configuration/limits-and-mdr'
      path: '/limits-and-mdr'
      fullPath: '/configuration/limits-and-mdr'
      preLoaderRoute: typeof AppConfigurationLimitsAndMdrRouteImport
      parentRoute: typeof AppConfigurationRoute
    }
    '/_app/configuration/email-sending': {
      id: '/_app/configuration/email-sending'
      path: '/email-sending'
      fullPath: '/configuration/email-sending'
      preLoaderRoute: typeof AppConfigurationEmailSendingRouteImport
      parentRoute: typeof AppConfigurationRoute
    }
    '/_app/configuration/case-triggering': {
      id: '/_app/configuration/case-triggering'
      path: '/case-triggering'
      fullPath: '/configuration/case-triggering'
      preLoaderRoute: typeof AppConfigurationCaseTriggeringRouteImport
      parentRoute: typeof AppConfigurationRoute
    }
    '/_app/configuration/case-flow-rules': {
      id: '/_app/configuration/case-flow-rules'
      path: '/case-flow-rules'
      fullPath: '/configuration/case-flow-rules'
      preLoaderRoute: typeof AppConfigurationCaseFlowRulesRouteImport
      parentRoute: typeof AppConfigurationRoute
    }
    '/_app/configuration/agreements': {
      id: '/_app/configuration/agreements'
      path: '/agreements'
      fullPath: '/configuration/agreements'
      preLoaderRoute: typeof AppConfigurationAgreementsRouteImport
      parentRoute: typeof AppConfigurationRoute
    }
    '/_app/cases/my-open-cases': {
      id: '/_app/cases/my-open-cases'
      path: '/my-open-cases'
      fullPath: '/cases/my-open-cases'
      preLoaderRoute: typeof AppCasesMyOpenCasesRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/_app/cases/my-closed-cases': {
      id: '/_app/cases/my-closed-cases'
      path: '/my-closed-cases'
      fullPath: '/cases/my-closed-cases'
      preLoaderRoute: typeof AppCasesMyClosedCasesRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/_app/cases/all-cases': {
      id: '/_app/cases/all-cases'
      path: '/all-cases'
      fullPath: '/cases/all-cases'
      preLoaderRoute: typeof AppCasesAllCasesRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/_app/user-management/users/$userId': {
      id: '/_app/user-management/users/$userId'
      path: '/users/$userId'
      fullPath: '/user-management/users/$userId'
      preLoaderRoute: typeof AppUserManagementUsersUserIdRouteImport
      parentRoute: typeof AppUserManagementRoute
    }
  }
}

interface AppCasesRouteChildren {
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRoute
  AppCasesAllCasesRoute: typeof AppCasesAllCasesRoute
  AppCasesMyClosedCasesRoute: typeof AppCasesMyClosedCasesRoute
  AppCasesMyOpenCasesRoute: typeof AppCasesMyOpenCasesRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
}

const AppCasesRouteChildren: AppCasesRouteChildren = {
  AppCasesCaseIdRoute: AppCasesCaseIdRoute,
  AppCasesAllCasesRoute: AppCasesAllCasesRoute,
  AppCasesMyClosedCasesRoute: AppCasesMyClosedCasesRoute,
  AppCasesMyOpenCasesRoute: AppCasesMyOpenCasesRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
}

const AppCasesRouteWithChildren = AppCasesRoute._addFileChildren(
  AppCasesRouteChildren,
)

interface AppConfigurationRouteChildren {
  AppConfigurationAgreementsRoute: typeof AppConfigurationAgreementsRoute
  AppConfigurationCaseFlowRulesRoute: typeof AppConfigurationCaseFlowRulesRoute
  AppConfigurationCaseTriggeringRoute: typeof AppConfigurationCaseTriggeringRoute
  AppConfigurationEmailSendingRoute: typeof AppConfigurationEmailSendingRoute
  AppConfigurationLimitsAndMdrRoute: typeof AppConfigurationLimitsAndMdrRoute
  AppConfigurationLinkDeadlinesRoute: typeof AppConfigurationLinkDeadlinesRoute
  AppConfigurationMerchantPortalRoute: typeof AppConfigurationMerchantPortalRoute
  AppConfigurationQueuesRoute: typeof AppConfigurationQueuesRoute
  AppConfigurationSubMerchantsRoute: typeof AppConfigurationSubMerchantsRoute
  AppConfigurationIndexRoute: typeof AppConfigurationIndexRoute
}

const AppConfigurationRouteChildren: AppConfigurationRouteChildren = {
  AppConfigurationAgreementsRoute: AppConfigurationAgreementsRoute,
  AppConfigurationCaseFlowRulesRoute: AppConfigurationCaseFlowRulesRoute,
  AppConfigurationCaseTriggeringRoute: AppConfigurationCaseTriggeringRoute,
  AppConfigurationEmailSendingRoute: AppConfigurationEmailSendingRoute,
  AppConfigurationLimitsAndMdrRoute: AppConfigurationLimitsAndMdrRoute,
  AppConfigurationLinkDeadlinesRoute: AppConfigurationLinkDeadlinesRoute,
  AppConfigurationMerchantPortalRoute: AppConfigurationMerchantPortalRoute,
  AppConfigurationQueuesRoute: AppConfigurationQueuesRoute,
  AppConfigurationSubMerchantsRoute: AppConfigurationSubMerchantsRoute,
  AppConfigurationIndexRoute: AppConfigurationIndexRoute,
}

const AppConfigurationRouteWithChildren =
  AppConfigurationRoute._addFileChildren(AppConfigurationRouteChildren)

interface AppMerchantsRouteChildren {
  AppMerchantsMerchantIdRoute: typeof AppMerchantsMerchantIdRoute
  AppMerchantsIndexRoute: typeof AppMerchantsIndexRoute
}

const AppMerchantsRouteChildren: AppMerchantsRouteChildren = {
  AppMerchantsMerchantIdRoute: AppMerchantsMerchantIdRoute,
  AppMerchantsIndexRoute: AppMerchantsIndexRoute,
}

const AppMerchantsRouteWithChildren = AppMerchantsRoute._addFileChildren(
  AppMerchantsRouteChildren,
)

interface AppUserManagementRouteChildren {
  AppUserManagementAllUsersRoute: typeof AppUserManagementAllUsersRoute
  AppUserManagementUserCreationRoute: typeof AppUserManagementUserCreationRoute
  AppUserManagementIndexRoute: typeof AppUserManagementIndexRoute
  AppUserManagementUsersUserIdRoute: typeof AppUserManagementUsersUserIdRoute
}

const AppUserManagementRouteChildren: AppUserManagementRouteChildren = {
  AppUserManagementAllUsersRoute: AppUserManagementAllUsersRoute,
  AppUserManagementUserCreationRoute: AppUserManagementUserCreationRoute,
  AppUserManagementIndexRoute: AppUserManagementIndexRoute,
  AppUserManagementUsersUserIdRoute: AppUserManagementUsersUserIdRoute,
}

const AppUserManagementRouteWithChildren =
  AppUserManagementRoute._addFileChildren(AppUserManagementRouteChildren)

interface AppRouteChildren {
  AppCasesRoute: typeof AppCasesRouteWithChildren
  AppConfigurationRoute: typeof AppConfigurationRouteWithChildren
  AppMerchantsRoute: typeof AppMerchantsRouteWithChildren
  AppUserManagementRoute: typeof AppUserManagementRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasesRoute: AppCasesRouteWithChildren,
  AppConfigurationRoute: AppConfigurationRouteWithChildren,
  AppMerchantsRoute: AppMerchantsRouteWithChildren,
  AppUserManagementRoute: AppUserManagementRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingFormRouteChildren {
  OnboardingFormIndexRoute: typeof OnboardingFormIndexRoute
  OnboardingFormAgreementTokenRoute: typeof OnboardingFormAgreementTokenRoute
  OnboardingFormGoLiveTokenRoute: typeof OnboardingFormGoLiveTokenRoute
  OnboardingFormResubmitTokenRoute: typeof OnboardingFormResubmitTokenRoute
}

const OnboardingFormRouteChildren: OnboardingFormRouteChildren = {
  OnboardingFormIndexRoute: OnboardingFormIndexRoute,
  OnboardingFormAgreementTokenRoute: OnboardingFormAgreementTokenRoute,
  OnboardingFormGoLiveTokenRoute: OnboardingFormGoLiveTokenRoute,
  OnboardingFormResubmitTokenRoute: OnboardingFormResubmitTokenRoute,
}

const OnboardingFormRouteWithChildren = OnboardingFormRoute._addFileChildren(
  OnboardingFormRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingFormRoute: OnboardingFormRouteWithChildren,
  SetPasswordTokenRoute: SetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
