/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingFormRouteImport } from './routes/onboarding-form'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUserManagementRouteImport } from './routes/_app.user-management'
import { Route as AppMerchantsRouteImport } from './routes/_app.merchants'
import { Route as AppCasesRouteImport } from './routes/_app.cases'
import { Route as AppUserManagementIndexRouteImport } from './routes/_app.user-management.index'
import { Route as AppMerchantsIndexRouteImport } from './routes/_app.merchants.index'
import { Route as AppCasesIndexRouteImport } from './routes/_app.cases.index'
import { Route as AppUserManagementUserCreationRouteImport } from './routes/_app.user-management.user-creation'
import { Route as AppUserManagementAllUsersRouteImport } from './routes/_app.user-management.all-users'
import { Route as AppUserManagementAccessPolicyRouteImport } from './routes/_app.user-management.access-policy'
import { Route as AppMerchantsMerchantIdRouteImport } from './routes/_app.merchants.$merchantId'
import { Route as AppCasesMyOpenCasesRouteImport } from './routes/_app.cases.my-open-cases'
import { Route as AppCasesMyClosedCasesRouteImport } from './routes/_app.cases.my-closed-cases'
import { Route as AppCasesAllCasesRouteImport } from './routes/_app.cases.all-cases'

const OnboardingFormRoute = OnboardingFormRouteImport.update({
  id: '/onboarding-form',
  path: '/onboarding-form',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUserManagementRoute = AppUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => AppRoute,
} as any)
const AppMerchantsRoute = AppMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppUserManagementIndexRoute = AppUserManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUserManagementRoute,
} as any)
const AppMerchantsIndexRoute = AppMerchantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMerchantsRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCasesRoute,
} as any)
const AppUserManagementUserCreationRoute =
  AppUserManagementUserCreationRouteImport.update({
    id: '/user-creation',
    path: '/user-creation',
    getParentRoute: () => AppUserManagementRoute,
  } as any)
const AppUserManagementAllUsersRoute =
  AppUserManagementAllUsersRouteImport.update({
    id: '/all-users',
    path: '/all-users',
    getParentRoute: () => AppUserManagementRoute,
  } as any)
const AppUserManagementAccessPolicyRoute =
  AppUserManagementAccessPolicyRouteImport.update({
    id: '/access-policy',
    path: '/access-policy',
    getParentRoute: () => AppUserManagementRoute,
  } as any)
const AppMerchantsMerchantIdRoute = AppMerchantsMerchantIdRouteImport.update({
  id: '/$merchantId',
  path: '/$merchantId',
  getParentRoute: () => AppMerchantsRoute,
} as any)
const AppCasesMyOpenCasesRoute = AppCasesMyOpenCasesRouteImport.update({
  id: '/my-open-cases',
  path: '/my-open-cases',
  getParentRoute: () => AppCasesRoute,
} as any)
const AppCasesMyClosedCasesRoute = AppCasesMyClosedCasesRouteImport.update({
  id: '/my-closed-cases',
  path: '/my-closed-cases',
  getParentRoute: () => AppCasesRoute,
} as any)
const AppCasesAllCasesRoute = AppCasesAllCasesRouteImport.update({
  id: '/all-cases',
  path: '/all-cases',
  getParentRoute: () => AppCasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding-form': typeof OnboardingFormRoute
  '/cases': typeof AppCasesRouteWithChildren
  '/merchants': typeof AppMerchantsRouteWithChildren
  '/user-management': typeof AppUserManagementRouteWithChildren
  '/cases/all-cases': typeof AppCasesAllCasesRoute
  '/cases/my-closed-cases': typeof AppCasesMyClosedCasesRoute
  '/cases/my-open-cases': typeof AppCasesMyOpenCasesRoute
  '/merchants/$merchantId': typeof AppMerchantsMerchantIdRoute
  '/user-management/access-policy': typeof AppUserManagementAccessPolicyRoute
  '/user-management/all-users': typeof AppUserManagementAllUsersRoute
  '/user-management/user-creation': typeof AppUserManagementUserCreationRoute
  '/cases/': typeof AppCasesIndexRoute
  '/merchants/': typeof AppMerchantsIndexRoute
  '/user-management/': typeof AppUserManagementIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding-form': typeof OnboardingFormRoute
  '/': typeof AppIndexRoute
  '/cases/all-cases': typeof AppCasesAllCasesRoute
  '/cases/my-closed-cases': typeof AppCasesMyClosedCasesRoute
  '/cases/my-open-cases': typeof AppCasesMyOpenCasesRoute
  '/merchants/$merchantId': typeof AppMerchantsMerchantIdRoute
  '/user-management/access-policy': typeof AppUserManagementAccessPolicyRoute
  '/user-management/all-users': typeof AppUserManagementAllUsersRoute
  '/user-management/user-creation': typeof AppUserManagementUserCreationRoute
  '/cases': typeof AppCasesIndexRoute
  '/merchants': typeof AppMerchantsIndexRoute
  '/user-management': typeof AppUserManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding-form': typeof OnboardingFormRoute
  '/_app/cases': typeof AppCasesRouteWithChildren
  '/_app/merchants': typeof AppMerchantsRouteWithChildren
  '/_app/user-management': typeof AppUserManagementRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/cases/all-cases': typeof AppCasesAllCasesRoute
  '/_app/cases/my-closed-cases': typeof AppCasesMyClosedCasesRoute
  '/_app/cases/my-open-cases': typeof AppCasesMyOpenCasesRoute
  '/_app/merchants/$merchantId': typeof AppMerchantsMerchantIdRoute
  '/_app/user-management/access-policy': typeof AppUserManagementAccessPolicyRoute
  '/_app/user-management/all-users': typeof AppUserManagementAllUsersRoute
  '/_app/user-management/user-creation': typeof AppUserManagementUserCreationRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/merchants/': typeof AppMerchantsIndexRoute
  '/_app/user-management/': typeof AppUserManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/onboarding-form'
    | '/cases'
    | '/merchants'
    | '/user-management'
    | '/cases/all-cases'
    | '/cases/my-closed-cases'
    | '/cases/my-open-cases'
    | '/merchants/$merchantId'
    | '/user-management/access-policy'
    | '/user-management/all-users'
    | '/user-management/user-creation'
    | '/cases/'
    | '/merchants/'
    | '/user-management/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/mcp'
    | '/onboarding-form'
    | '/'
    | '/cases/all-cases'
    | '/cases/my-closed-cases'
    | '/cases/my-open-cases'
    | '/merchants/$merchantId'
    | '/user-management/access-policy'
    | '/user-management/all-users'
    | '/user-management/user-creation'
    | '/cases'
    | '/merchants'
    | '/user-management'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/mcp'
    | '/onboarding-form'
    | '/_app/cases'
    | '/_app/merchants'
    | '/_app/user-management'
    | '/_app/'
    | '/_app/cases/all-cases'
    | '/_app/cases/my-closed-cases'
    | '/_app/cases/my-open-cases'
    | '/_app/merchants/$merchantId'
    | '/_app/user-management/access-policy'
    | '/_app/user-management/all-users'
    | '/_app/user-management/user-creation'
    | '/_app/cases/'
    | '/_app/merchants/'
    | '/_app/user-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingFormRoute: typeof OnboardingFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding-form': {
      id: '/onboarding-form'
      path: '/onboarding-form'
      fullPath: '/onboarding-form'
      preLoaderRoute: typeof OnboardingFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user-management': {
      id: '/_app/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AppUserManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/merchants': {
      id: '/_app/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof AppMerchantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user-management/': {
      id: '/_app/user-management/'
      path: '/'
      fullPath: '/user-management/'
      preLoaderRoute: typeof AppUserManagementIndexRouteImport
      parentRoute: typeof AppUserManagementRoute
    }
    '/_app/merchants/': {
      id: '/_app/merchants/'
      path: '/'
      fullPath: '/merchants/'
      preLoaderRoute: typeof AppMerchantsIndexRouteImport
      parentRoute: typeof AppMerchantsRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/_app/user-management/user-creation': {
      id: '/_app/user-management/user-creation'
      path: '/user-creation'
      fullPath: '/user-management/user-creation'
      preLoaderRoute: typeof AppUserManagementUserCreationRouteImport
      parentRoute: typeof AppUserManagementRoute
    }
    '/_app/user-management/all-users': {
      id: '/_app/user-management/all-users'
      path: '/all-users'
      fullPath: '/user-management/all-users'
      preLoaderRoute: typeof AppUserManagementAllUsersRouteImport
      parentRoute: typeof AppUserManagementRoute
    }
    '/_app/user-management/access-policy': {
      id: '/_app/user-management/access-policy'
      path: '/access-policy'
      fullPath: '/user-management/access-policy'
      preLoaderRoute: typeof AppUserManagementAccessPolicyRouteImport
      parentRoute: typeof AppUserManagementRoute
    }
    '/_app/merchants/$merchantId': {
      id: '/_app/merchants/$merchantId'
      path: '/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof AppMerchantsMerchantIdRouteImport
      parentRoute: typeof AppMerchantsRoute
    }
    '/_app/cases/my-open-cases': {
      id: '/_app/cases/my-open-cases'
      path: '/my-open-cases'
      fullPath: '/cases/my-open-cases'
      preLoaderRoute: typeof AppCasesMyOpenCasesRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/_app/cases/my-closed-cases': {
      id: '/_app/cases/my-closed-cases'
      path: '/my-closed-cases'
      fullPath: '/cases/my-closed-cases'
      preLoaderRoute: typeof AppCasesMyClosedCasesRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/_app/cases/all-cases': {
      id: '/_app/cases/all-cases'
      path: '/all-cases'
      fullPath: '/cases/all-cases'
      preLoaderRoute: typeof AppCasesAllCasesRouteImport
      parentRoute: typeof AppCasesRoute
    }
  }
}

interface AppCasesRouteChildren {
  AppCasesAllCasesRoute: typeof AppCasesAllCasesRoute
  AppCasesMyClosedCasesRoute: typeof AppCasesMyClosedCasesRoute
  AppCasesMyOpenCasesRoute: typeof AppCasesMyOpenCasesRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
}

const AppCasesRouteChildren: AppCasesRouteChildren = {
  AppCasesAllCasesRoute: AppCasesAllCasesRoute,
  AppCasesMyClosedCasesRoute: AppCasesMyClosedCasesRoute,
  AppCasesMyOpenCasesRoute: AppCasesMyOpenCasesRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
}

const AppCasesRouteWithChildren = AppCasesRoute._addFileChildren(
  AppCasesRouteChildren,
)

interface AppMerchantsRouteChildren {
  AppMerchantsMerchantIdRoute: typeof AppMerchantsMerchantIdRoute
  AppMerchantsIndexRoute: typeof AppMerchantsIndexRoute
}

const AppMerchantsRouteChildren: AppMerchantsRouteChildren = {
  AppMerchantsMerchantIdRoute: AppMerchantsMerchantIdRoute,
  AppMerchantsIndexRoute: AppMerchantsIndexRoute,
}

const AppMerchantsRouteWithChildren = AppMerchantsRoute._addFileChildren(
  AppMerchantsRouteChildren,
)

interface AppUserManagementRouteChildren {
  AppUserManagementAccessPolicyRoute: typeof AppUserManagementAccessPolicyRoute
  AppUserManagementAllUsersRoute: typeof AppUserManagementAllUsersRoute
  AppUserManagementUserCreationRoute: typeof AppUserManagementUserCreationRoute
  AppUserManagementIndexRoute: typeof AppUserManagementIndexRoute
}

const AppUserManagementRouteChildren: AppUserManagementRouteChildren = {
  AppUserManagementAccessPolicyRoute: AppUserManagementAccessPolicyRoute,
  AppUserManagementAllUsersRoute: AppUserManagementAllUsersRoute,
  AppUserManagementUserCreationRoute: AppUserManagementUserCreationRoute,
  AppUserManagementIndexRoute: AppUserManagementIndexRoute,
}

const AppUserManagementRouteWithChildren =
  AppUserManagementRoute._addFileChildren(AppUserManagementRouteChildren)

interface AppRouteChildren {
  AppCasesRoute: typeof AppCasesRouteWithChildren
  AppMerchantsRoute: typeof AppMerchantsRouteWithChildren
  AppUserManagementRoute: typeof AppUserManagementRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasesRoute: AppCasesRouteWithChildren,
  AppMerchantsRoute: AppMerchantsRouteWithChildren,
  AppUserManagementRoute: AppUserManagementRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingFormRoute: OnboardingFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
